### ISSUE TITLE
Visualizer crashes whenever sound is being played

### ISSUE THREAD

**Issue by ShadowAriaa** [alatsombath/Fountain-of-Colors#16]
https://streamable.com/9ey4m

OS: Windows 10 Pro
Rainmeter Version: Latest (4.3 Beta Release - 3279)

Visualizer downloaded from DeviantArt

**Comment by ShadowAriaa** [comment]
In the final version of Rainmeter it doesn't show up at all

**Comment by SnGmng** [comment]
can you provide rainmeter logs?

**Comment by ShadowAriaa** [comment]
![image](https://user-images.githubusercontent.com/17110757/52180503-65c74e80-27e7-11e9-93fe-7d332bcc1cf1.png)

**Comment by SnGmng** [comment]
I would recommend looking at the [known issues](https://forum.rainmeter.net/viewtopic.php?t=23348) first if you have not already done so. I also looked up the error message in the [AudioLevel plugin source code](https://gist.github.com/alatsombath/da3c4df491ea9a39f570c83def64bb8a) and it seems that the IAudioClient most likely can not be initialized because of a wrong waveformat (your audio device could not be recognized) , Unfortunately I can not reproduce your problem so I can not debug it either.
You can either debug it yourself by building the [AudioLevel plugin source code](https://gist.github.com/alatsombath/da3c4df491ea9a39f570c83def64bb8a) or just wait for alatsombath to fix the problem or add more debug information.
